### ISSUE TITLE
Copy all the files to the keycloak theme directory

### ISSUE THREAD

**Issue by hendisantika** [alxrodav/keycloak-theme#2]
Is it ok to Copy all the files to the keycloak theme directory?

If that so I have error.

**Comment by alexrdguez91** [comment]
Hello @hendisantika the last time I touched this code was 2 years ago. Unfortunately, I would not be a good help to you.
Did you try to contact the Keycloak team directly?
https://github.com/keycloak/keycloak

**Comment by hendisantika** [comment]
OK. Thanks @alexrdguez91
